# Generated by Django 4.1.1 on 2022-09-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesmericanas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
