# Generated by Django 4.1.1 on 2022-09-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesmericanas', '0002_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
    ]
